#define DISPLAY_HEIGHT (160)
#define DISPLAY_WIDTH (240)

#define TILE_PIXEL_SIDE (8)

#define DISPLAY_HEIGHT_TILES (DISPLAY_HEIGHT / TILE_PIXEL_SIDE)
#define DISPLAY_WIDTH_TILES (DISPLAY_WIDTH / TILE_PIXEL_SIDE)

#define VCOUNT_MAX (227)
